name: Flutter Build and Upload Android APK Yuhua Jin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install yq
        uses: mikefarah/yq@v4.42.1

      - name: Get pubspec version
        id: get_flutter_app_version
        run: |
          VERSION=$(yq .version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' pubspec.yaml | head -n 1)
          echo "TAG_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create git tag
        run: |
          git tag "v${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'main'

      - name: Change to Flutter project directory
        run: culture_pulse_app

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Build an AppBundle
        run: flutter build appbundle --release

      - name: Save APK to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-apk
          path: culture_pulse_app/build/app/outputs/flutter-apk/*.apk

      - name: Save AppBundle to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-appbundle
          path: culture_pulse_app/build/app/outputs/bundle/release/*.aab

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}"
          release_name: "v${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}"
          body: "Release version v${{ steps.get_flutter_app_version.outputs.TAG_VERSION }}"